export type CalculatorDefinition = { slug:string; name:string; description:string; category:string; keywords:string[]; icon:string; popular?:boolean; fields:Array<{key:string;label:string;default:number;min?:number;max?:number;step?:number;suffix?:string}>; resultLabel:string; related:string[] };
const f=(key:string,label:string,value:number,suffix="",step=1)=>({key,label,default:value,suffix,step,min:0});
export const calculators: CalculatorDefinition[] = [
 {slug:"emi-calculator",name:"EMI Calculator",description:"Plan loan payments, interest, and payoff.",category:"Loans",keywords:["loan","mortgage","monthly"],icon:"Landmark",popular:true,fields:[f("principal","Loan amount",2500000,"₹",10000),f("rate","Interest rate",8.5,"%",.1),f("years","Tenure",20,"years")],resultLabel:"Monthly EMI",related:["loan-eligibility-calculator","home-affordability-calculator"]},
 {slug:"sip-calculator",name:"SIP Calculator",description:"Project long-term mutual fund wealth.",category:"Investing",keywords:["mutual fund","returns","monthly"],icon:"TrendingUp",popular:true,fields:[f("monthly","Monthly investment",10000,"₹",500),f("rate","Expected return",12,"%",.5),f("years","Time period",10,"years")],resultLabel:"Future value",related:["cagr-calculator","retirement-calculator"]},
 {slug:"fd-calculator",name:"FD Calculator",description:"Estimate fixed deposit maturity value.",category:"Investing",keywords:["deposit","interest","bank"],icon:"PiggyBank",fields:[f("principal","Deposit",100000,"₹",1000),f("rate","Interest rate",7,"%",.1),f("years","Tenure",5,"years")],resultLabel:"Maturity value",related:["sip-calculator","cagr-calculator"]},
 {slug:"cagr-calculator",name:"CAGR Calculator",description:"Measure annualized investment growth.",category:"Investing",keywords:["growth","annual","return"],icon:"ChartNoAxesCombined",fields:[f("start","Initial value",100000,"₹",1000),f("end","Final value",200000,"₹",1000),f("years","Years",5,"years")],resultLabel:"Annual growth",related:["sip-calculator","fd-calculator"]},
 {slug:"inflation-calculator",name:"Inflation Calculator",description:"See how rising prices change purchasing power.",category:"Planning",keywords:["cost","future value","purchasing"],icon:"ChartSpline",fields:[f("amount","Current cost",100000,"₹",1000),f("rate","Inflation",6,"%",.1),f("years","Years",10,"years")],resultLabel:"Future cost",related:["retirement-calculator","sip-calculator"]},
 {slug:"retirement-calculator",name:"Retirement Calculator",description:"Estimate the corpus needed for retirement.",category:"Planning",keywords:["corpus","future","pension"],icon:"Sunset",popular:true,fields:[f("expense","Monthly expense today",50000,"₹",1000),f("years","Years to retirement",25,"years"),f("inflation","Inflation",6,"%",.1),f("return","Post-retirement return",8,"%",.1)],resultLabel:"Target corpus",related:["sip-calculator","inflation-calculator"]},
 {slug:"emergency-fund-calculator",name:"Emergency Fund Calculator",description:"Build a safety buffer around your lifestyle.",category:"Planning",keywords:["safety","expenses","buffer"],icon:"ShieldCheck",fields:[f("expense","Essential monthly expenses",45000,"₹",1000),f("months","Months of cover",6,"months")],resultLabel:"Fund target",related:["net-worth-calculator","retirement-calculator"]},
 {slug:"net-worth-calculator",name:"Net Worth Calculator",description:"Get a clear snapshot of assets minus liabilities.",category:"Planning",keywords:["assets","liabilities","wealth"],icon:"WalletCards",fields:[f("assets","Total assets",3500000,"₹",10000),f("liabilities","Total liabilities",1200000,"₹",10000)],resultLabel:"Your net worth",related:["emergency-fund-calculator","home-affordability-calculator"]},
 {slug:"loan-eligibility-calculator",name:"Loan Eligibility Calculator",description:"Estimate a comfortable maximum loan.",category:"Loans",keywords:["salary","emi","borrow"],icon:"BadgeIndianRupee",fields:[f("income","Monthly income",100000,"₹",1000),f("obligations","Existing monthly EMIs",10000,"₹",1000),f("rate","Interest rate",9,"%",.1),f("years","Tenure",20,"years")],resultLabel:"Eligible loan",related:["emi-calculator","home-affordability-calculator"]},
 {slug:"home-affordability-calculator",name:"Home Affordability Calculator",description:"Find a responsible home-buying budget.",category:"Loans",keywords:["house","property","down payment"],icon:"House",fields:[f("income","Monthly household income",150000,"₹",1000),f("savings","Down payment savings",1500000,"₹",10000),f("obligations","Monthly obligations",15000,"₹",1000)],resultLabel:"Affordable home",related:["emi-calculator","loan-eligibility-calculator"]},
 {slug:"gst-calculator",name:"GST Calculator",description:"Add or remove Goods and Services Tax.",category:"Tax",keywords:["tax","invoice","goods"],icon:"ReceiptIndianRupee",fields:[f("amount","Base amount",10000,"₹",100),f("rate","GST rate",18,"%")],resultLabel:"Total with GST",related:["income-tax-calculator","percentage-calculator"]},
 {slug:"income-tax-calculator",name:"Income Tax Basic Calculator",description:"Quick simplified new-regime tax estimate.",category:"Tax",keywords:["salary","income","india"],icon:"FileText",fields:[f("income","Annual taxable income",1200000,"₹",10000)],resultLabel:"Estimated tax",related:["hra-calculator","gst-calculator"]},
 {slug:"hra-calculator",name:"HRA Basic Calculator",description:"Estimate HRA exemption using standard rules.",category:"Tax",keywords:["rent","salary","exemption"],icon:"Building2",fields:[f("hra","Annual HRA received",240000,"₹",1000),f("rent","Annual rent paid",300000,"₹",1000),f("basic","Annual basic salary",600000,"₹",1000),f("metro","Metro city (1=yes)",1,"0/1")],resultLabel:"HRA exemption",related:["income-tax-calculator","home-affordability-calculator"]},
 {slug:"age-calculator",name:"Age Calculator",description:"Estimate your age from birth and comparison years.",category:"Everyday",keywords:["birthday","years","date"],icon:"CakeSlice",fields:[f("birthYear","Birth year",1995,"year"),f("currentYear","Comparison year",new Date().getFullYear(),"year")],resultLabel:"Your age",related:["percentage-calculator","bmi-calculator"]},
 {slug:"percentage-calculator",name:"Percentage Calculator",description:"Find a percentage of any number.",category:"Everyday",keywords:["percent","math","ratio"],icon:"Percent",fields:[f("value","Value",5000,""),f("percentage","Percentage",18,"%")],resultLabel:"Result",related:["discount-calculator","gst-calculator"]},
 {slug:"discount-calculator",name:"Discount Calculator",description:"See sale price and savings instantly.",category:"Everyday",keywords:["sale","saving","price"],icon:"BadgePercent",fields:[f("price","Original price",4999,"₹"),f("discount","Discount",25,"%")],resultLabel:"Sale price",related:["percentage-calculator","gst-calculator"]},
 {slug:"bmi-calculator",name:"BMI Calculator",description:"Check body mass index and healthy range.",category:"Health",keywords:["weight","height","fitness"],icon:"Activity",fields:[f("weight","Weight",70,"kg",.5),f("height","Height",175,"cm")],resultLabel:"Your BMI",related:["age-calculator","percentage-calculator"]},
 {slug:"fuel-cost-calculator",name:"Fuel Cost Calculator",description:"Estimate fuel spend for a journey.",category:"Everyday",keywords:["petrol","trip","mileage"],icon:"Fuel",fields:[f("distance","Distance",500,"km"),f("mileage","Vehicle mileage",15,"km/L",.5),f("price","Fuel price",105,"₹/L",.1)],resultLabel:"Trip fuel cost",related:["percentage-calculator","discount-calculator"]},
 {slug:"unit-converter",name:"Unit Converter",description:"Convert common length measurements.",category:"Everyday",keywords:["length","meters","feet"],icon:"Ruler",fields:[f("value","Meters",10,"m",.1)],resultLabel:"Feet",related:["percentage-calculator","age-calculator"]},
 {slug:"currency-converter",name:"Currency Converter Mock",description:"Preview a clean currency conversion flow.",category:"Everyday",keywords:["money","exchange","forex"],icon:"ArrowLeftRight",fields:[f("amount","USD amount",100,"USD",1),f("rate","Demo USD/INR rate",83.5,"₹",.1)],resultLabel:"INR value",related:["gst-calculator","percentage-calculator"]}
];
export const calculatorBySlug = (slug:string) => calculators.find(x=>x.slug===slug);
export const searchCalculators = (q:string) => { const n=q.toLowerCase().trim(); return !n?calculators:calculators.filter(x=>[x.name,x.slug,x.category,x.description,...x.keywords].join(" ").toLowerCase().includes(n)); };
