"use client";
import * as React from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Calculator, Check, ChevronRight, Clock3, Compass, Copy, Heart, Home, Layers3, Menu, Search, Sparkles, UserRound, Wrench, X } from "lucide-react";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from "recharts";
import { cn, formatINR, formatNumber } from "@datastorified/utils";

export function Button({className,variant="primary",children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"|"danger"}){return <button className={cn("inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition-all disabled:cursor-not-allowed disabled:opacity-50",variant==="primary"&&"bg-gradient-to-br from-primary to-accent text-white shadow-glow hover:-translate-y-0.5",variant==="secondary"&&"border border-border bg-white text-ink shadow-soft hover:border-primary/30",variant==="ghost"&&"text-muted hover:bg-soft hover:text-ink",variant==="danger"&&"bg-danger text-white",className)} {...props}>{children}</button>}
export function Card({className,children,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("rounded-3xl border border-border/80 bg-white shadow-soft",className)} {...props}>{children}</div>}
export function Input({className,...props}:React.InputHTMLAttributes<HTMLInputElement>){return <input className={cn("min-h-12 w-full rounded-xl border border-border bg-white px-4 text-base text-ink outline-none transition placeholder:text-muted/70 focus:border-primary focus:ring-4 focus:ring-primary/10",className)} {...props}/>}
export function Textarea({className,...props}:React.TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea className={cn("min-h-44 w-full resize-y rounded-2xl border border-border bg-white p-4 text-base leading-7 text-ink outline-none transition placeholder:text-muted/70 focus:border-primary focus:ring-4 focus:ring-primary/10",className)} {...props}/>}
export function Badge({children,className}:React.HTMLAttributes<HTMLSpanElement>){return <span className={cn("inline-flex items-center rounded-full border border-primary/10 bg-primary/5 px-3 py-1 text-xs font-semibold text-primary",className)}>{children}</span>}
export function Tabs({items,value,onChange}:{items:string[];value:string;onChange:(x:string)=>void}){return <div className="flex gap-1 overflow-x-auto rounded-xl bg-soft p-1">{items.map(x=><button key={x} onClick={()=>onChange(x)} className={cn("min-h-10 whitespace-nowrap rounded-lg px-3 text-sm font-semibold transition",value===x?"bg-white text-ink shadow-sm":"text-muted")}>{x}</button>)}</div>}
export function BrandMark({className}:{className?:string}){return <span className={cn("grid shrink-0 place-items-center overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-border/60",className)}><img src="/brand/mark.png" alt="" aria-hidden="true" className="size-full object-contain p-1" /></span>}

export function Header({active="home",surface="website"}:{active?:string;surface?:"website"|"calculators"|"tools"}){
 void active;
 const [open,setOpen]=React.useState(false);const home=surface==="website"?"/":surface==="calculators"?"/":"/";
 const links=surface==="website"?[{label:"Decisions",href:"/#decisions"},{label:"Calculators",href:"https://calculators.datastorified.com"},{label:"Tools",href:"https://tools.datastorified.com"},{label:"About",href:"/about"},{label:"Trust",href:"/trust"}]:[{label:"Explore",href:"/"},{label:"Categories",href:"/#categories"},{label:"Recent",href:"/#recent"}];
 return <header className="sticky top-0 z-50 border-b border-border/70 bg-white/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><Link href={home} className="flex items-center gap-2 font-bold tracking-tight text-ink"><BrandMark className="size-10"/><span>DataStorified</span>{surface!=="website"&&<Badge className="hidden sm:inline-flex">{surface}</Badge>}</Link><nav className="hidden items-center gap-1 lg:flex">{links.map(x=><Link key={x.label} className="rounded-lg px-3 py-2 text-sm font-medium text-muted transition hover:bg-soft hover:text-ink" href={x.href}>{x.label}</Link>)}<Button variant="secondary" className="ml-2"><UserRound size={16}/> Sign in to sync</Button></nav><button aria-label="Open menu" className="grid size-11 place-items-center lg:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.nav initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden border-t border-border bg-white px-4 py-3 lg:hidden">{links.map(x=><Link onClick={()=>setOpen(false)} className="block rounded-xl px-3 py-3 font-medium text-muted" key={x.label} href={x.href}>{x.label}</Link>)}<p className="px-3 py-2 text-sm text-muted">Sign in to sync across devices</p></motion.nav>}</AnimatePresence></header>
}
export function Footer(){const legal=[['Privacy','privacy'],['Terms','terms'],['Cookies','cookies'],['Disclaimer','disclaimer'],['AI Disclosure','ai-disclosure'],['Security','security']];return <footer className="border-t border-border bg-white pb-24 pt-12 md:pb-12"><div className="mx-auto grid max-w-7xl gap-9 px-4 sm:grid-cols-2 sm:px-6 lg:grid-cols-[1.4fr_1fr_1fr_1.35fr]"><div><div className="flex items-center gap-2 font-bold"><BrandMark className="size-9"/>DataStorified</div><p className="mt-3 max-w-sm text-sm leading-6 text-muted">Decision intelligence and useful everyday tools, designed to make the next move feel clearer.</p><p className="mt-4 text-xs leading-5 text-muted">Private by default. Drafts, favorites, and history stay in this browser.</p></div><div><p className="font-semibold">Product</p><div className="mt-3 flex flex-col gap-2.5 text-sm text-muted"><a className="hover:text-primary" href="https://datastorified.com/#decisions">Decision engine</a><a className="hover:text-primary" href="https://calculators.datastorified.com">Smart calculators</a><a className="hover:text-primary" href="https://tools.datastorified.com">Online tools</a></div></div><div><p className="font-semibold">Company</p><div className="mt-3 flex flex-col gap-2.5 text-sm text-muted"><a className="hover:text-primary" href="https://datastorified.com/about">About</a><a className="hover:text-primary" href="https://datastorified.com/trust">Trust Center</a><a className="hover:text-primary" href="https://datastorified.com/contact">Contact</a><a className="hover:text-primary" href="https://datastorified.com/legal">Legal hub</a></div></div><div><p className="font-semibold">Legal</p><div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2.5 text-sm text-muted">{legal.map(([label,slug])=><a className="hover:text-primary" key={slug} href={`https://datastorified.com/legal/${slug}`}>{label}</a>)}<a className="hover:text-primary" href="https://datastorified.com/contact">Contact</a></div></div></div><div className="mx-auto mt-10 flex max-w-7xl flex-col gap-2 border-t border-border px-4 pt-6 text-xs text-muted sm:flex-row sm:items-center sm:justify-between sm:px-6"><span>© {new Date().getFullYear()} DataStorified</span><span>Built for clearer decisions.</span></div></footer>}
export function BottomNav({active="home"}:{active?:string}){const items=[{x:"home",l:"Home",i:Home,h:"/"},{x:"search",l:"Search",i:Search,h:"/#search"},{x:"categories",l:"Categories",i:Layers3,h:"/#categories"},{x:"recent",l:"Recent",i:Clock3,h:"/#recent"},{x:"profile",l:"Profile",i:UserRound,h:"/#profile"}];return <nav className="fixed inset-x-0 bottom-0 z-50 border-t border-border bg-white/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur-xl md:hidden"><div className="mx-auto flex max-w-md justify-around">{items.map(({x,l,i:I,h})=><Link href={h} key={x} className={cn("flex min-w-14 flex-col items-center gap-1 rounded-xl py-1.5 text-[11px] font-medium",active===x?"text-primary":"text-muted")}><I size={20}/>{l}</Link>)}</div></nav>}

export function SearchBox({value,onChange,placeholder,onSubmit,large=false}:{value:string;onChange:(x:string)=>void;placeholder:string;onSubmit?:()=>void;large?:boolean}){return <div className={cn("group flex items-center gap-3 rounded-2xl border border-border bg-white p-2 shadow-soft transition focus-within:border-primary/40 focus-within:shadow-glow",large&&"rounded-3xl p-2.5")}><Search className="ml-2 shrink-0 text-muted" size={large?22:19}/><input id="search" value={value} onChange={e=>onChange(e.target.value)} onKeyDown={e=>e.key==="Enter"&&onSubmit?.()} placeholder={placeholder} className={cn("min-w-0 flex-1 bg-transparent px-1 text-base outline-none placeholder:text-muted/70",large&&"min-h-12 sm:text-lg")}/>{value&&<button className="grid size-9 place-items-center text-muted" onClick={()=>onChange("")}><X size={17}/></button>}{onSubmit&&<Button onClick={onSubmit} className="hidden sm:inline-flex">Explore <ArrowRight size={16}/></Button>}</div>}
export type ItemCardProps={name:string;description:string;category:string;href:string;favorite?:boolean;onFavorite?:()=>void;icon?:React.ReactNode};
export function ExplorerCard({name,description,category,href,favorite,onFavorite,icon}:ItemCardProps){return <motion.div whileHover={{y:-4}} transition={{duration:.18}} className="group relative h-full"><Link href={href} className="block h-full"><Card className="h-full p-5 transition group-hover:border-primary/20 group-hover:shadow-lift"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-gradient-to-br from-primary/10 to-accent/10 text-primary">{icon||<Sparkles size={20}/>}</span><ChevronRight size={18} className="mt-2 text-muted/50 transition group-hover:translate-x-1 group-hover:text-primary"/></div><Badge className="mt-5">{category}</Badge><h3 className="mt-3 text-lg font-bold tracking-tight text-ink">{name}</h3><p className="mt-1.5 text-sm leading-6 text-muted">{description}</p></Card></Link>{onFavorite&&<button aria-label="Favorite" onClick={e=>{e.preventDefault();onFavorite()}} className="absolute right-11 top-6 grid size-8 place-items-center rounded-full text-muted transition hover:bg-soft hover:text-danger"><Heart size={17} className={favorite?"fill-danger text-danger":""}/></button>}</motion.div>}
export const CalculatorCard=(p:ItemCardProps)=><ExplorerCard {...p} icon={p.icon||<Calculator size={20}/>}/>;
export const ToolCard=(p:ItemCardProps)=><ExplorerCard {...p} icon={p.icon||<Wrench size={20}/>}/>;
export function CategorySection({title,description,children,id}:{title:string;description?:string;children:React.ReactNode;id?:string}){return <section id={id} className="scroll-mt-24"><div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-bold tracking-tight text-ink sm:text-3xl">{title}</h2>{description&&<p className="mt-2 text-muted">{description}</p>}</div></div>{children}</section>}
export function ResultCard({label,value,unit="currency",suffix,secondary=[]}:{label:string;value:number;unit?:"currency"|"percent"|"number";suffix?:string;secondary?:Array<{label:string;value:number;unit?:"currency"|"percent"|"number";suffix?:string}>}){const format=(n:number,u=unit)=>u==="currency"?formatINR(n):u==="percent"?`${formatNumber(n,2)}%`:formatNumber(n,2);return <motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} key={`${value}-${suffix}`}><Card className="overflow-hidden border-0 bg-gradient-to-br from-primary to-accent p-6 text-white shadow-glow sm:p-8"><p className="text-sm font-medium text-white/75">{label}</p><p className="mt-2 break-words text-4xl font-bold tracking-tight sm:text-5xl">{format(value)}{suffix&&<span className="ml-2 text-lg font-semibold text-white/75 sm:text-xl">{suffix}</span>}</p>{secondary.length>0&&<div className="mt-6 grid grid-cols-2 gap-3 border-t border-white/20 pt-5">{secondary.map(x=><div key={x.label}><p className="text-xs text-white/65">{x.label}</p><p className="mt-1 font-semibold">{format(x.value,x.unit)}{x.suffix&&<span className="ml-1 text-xs text-white/70">{x.suffix}</span>}</p></div>)}</div>}</Card></motion.div>}
export function InsightCard({children,title="DataStorified insight"}:{children:React.ReactNode;title?:string}){return <Card className="border-primary/15 bg-gradient-to-br from-primary/[.06] to-accent/[.07] p-5"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-accent shadow-sm"><Sparkles size={18}/></span><div><p className="font-semibold text-ink">{title}</p><div className="mt-1 text-sm leading-6 text-muted">{children}</div></div></div></Card>}
export function ChartCard({data,title="Visual breakdown"}:{data:Array<{name:string;value:number}>;title?:string}){const colors=["#2563EB","#7C3AED","#10B981"];return <Card className="p-5"><p className="font-semibold">{title}</p><div className="mt-3 flex h-52 items-center"><div className="h-full flex-1"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={48} outerRadius={76} paddingAngle={3}>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v)=>formatINR(Number(v))}/></PieChart></ResponsiveContainer></div><div className="space-y-3">{data.map((x,i)=><div key={x.name} className="flex items-center gap-2 text-sm"><span className="size-2.5 rounded-full" style={{background:colors[i%colors.length]}}/><span className="text-muted">{x.name}</span></div>)}</div></div></Card>}
export function Breadcrumb({items}:{items:Array<{label:string;href?:string}>}){return <nav className="flex flex-wrap items-center gap-1.5 text-sm text-muted">{items.map((x,i)=><React.Fragment key={x.label}>{i>0&&<ChevronRight size={14}/>} {x.href?<Link className="hover:text-primary" href={x.href}>{x.label}</Link>:<span className="text-ink">{x.label}</span>}</React.Fragment>)}</nav>}
export function FAQ({items}:{items:Array<{question:string;answer:string}>}){return <div className="space-y-3">{items.map((x,i)=><details key={i} className="group rounded-2xl border border-border bg-white p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold">{x.question}<span className="text-primary transition group-open:rotate-45">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">{x.answer}</p></details>)}</div>}
export function EmptyState({title="Nothing here yet",description="Try another search or explore a category."}:{title?:string;description?:string}){return <Card className="grid place-items-center p-10 text-center"><Compass className="text-primary"/><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 text-sm text-muted">{description}</p></Card>}
export function CopyButton({value}:{value:string}){const [done,setDone]=React.useState(false);return <Button variant="secondary" onClick={async()=>{await navigator.clipboard.writeText(value);setDone(true);setTimeout(()=>setDone(false),1500)}}>{done?<Check size={16}/>:<Copy size={16}/>} {done?"Copied":"Copy"}</Button>}
