import { ArrowRight, BrainCircuit, Calculator, CheckCircle2, ShieldCheck, SlidersHorizontal, Wrench } from "lucide-react";
import { Badge, BottomNav, Button, Card, Footer, Header } from "@datastorified/ui";
import { decisionPluginRegistry } from "@datastorified/decision-os";
import { DecisionHero } from "../components/decision/DecisionHero";
import { DecisionSuggestionCard } from "../components/decision/DecisionSuggestionCard";
import { DecisionRecent } from "../components/decision/DecisionRecent";

const popularSlugs = ["buy-house", "rent-vs-buy", "sip-vs-fd", "emergency-fund", "loan-prepayment", "ev-vs-petrol", "buy-car", "job-switch"];
const popular = popularSlugs.map((slug) => decisionPluginRegistry.getWorkflowBySlug(slug)).filter(Boolean);

export default function Home() {
  return <><Header /><main><DecisionHero /><section id="decisions" className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge>Popular decisions</Badge><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">A clearer next move starts here</h2><p className="mt-2 max-w-2xl leading-7 text-muted">Eight working flows cover money, property, vehicles, and career choices with transparent scoring.</p></div><a href="/decision"><Button variant="secondary">Explore Decision OS <ArrowRight size={16} /></Button></a></div><div className="mt-8 grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-4">{popular.map((workflow) => workflow && <DecisionSuggestionCard key={workflow.id} workflow={workflow} />)}</div></section><div id="recent"><DecisionRecent /></div><section className="bg-soft py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="text-center"><Badge>How it works</Badge><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Evidence in. Explainable decision out.</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{[[BrainCircuit, "Answer focused questions", "One question at a time on mobile, with no black-box prompts."], [CheckCircle2, "See score and risk", "Weighted factors explain what supports or weakens the choice."], [SlidersHorizontal, "Challenge the result", "Change key assumptions before you commit."]].map(([Icon, title, body]) => { const I = Icon as typeof BrainCircuit; return <Card key={String(title)} className="p-6"><I className="text-primary" /><h3 className="mt-4 text-xl font-bold">{String(title)}</h3><p className="mt-2 leading-7 text-muted">{String(body)}</p></Card>; })}</div></div></section><section className="mx-auto grid max-w-7xl gap-6 px-4 py-16 sm:px-6 lg:grid-cols-2"><Shortcut icon={<Calculator />} title="Smart calculators" body="Go deeper on EMI, SIP, affordability, tax, vehicles, and more." href="https://calculators.datastorified.com" /><Shortcut icon={<Wrench />} title="Everyday tools" body="Fast, private utilities for text, files, code, and small jobs." href="https://tools.datastorified.com" /></section><section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6"><Card className="flex flex-col gap-5 bg-gradient-to-br from-primary/[.06] to-accent/[.08] p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div className="flex gap-4"><ShieldCheck className="shrink-0 text-primary" /><div><h2 className="text-xl font-bold">Private by default</h2><p className="mt-1 text-muted">Decision drafts and results stay on this device. No login, backend, or AI is required.</p></div></div><a href="/trust"><Button variant="secondary">How trust works</Button></a></Card></section></main><Footer /><BottomNav /></>;
}

function Shortcut({ icon, title, body, href }: { icon: React.ReactNode; title: string; body: string; href: string }) {
  return <Card className="p-6 sm:p-8"><span className="grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-primary to-accent text-white">{icon}</span><h2 className="mt-5 text-2xl font-bold">{title}</h2><p className="mt-2 leading-7 text-muted">{body}</p><a href={href} className="mt-5 inline-block"><Button variant="secondary">Explore all <ArrowRight size={16} /></Button></a></Card>;
}
