export type ToolDefinition={slug:string;name:string;description:string;category:"Text"|"Developer"|"Image"|"PDF"|"Utility";keywords:string[];icon:string;mode:string;popular?:boolean;mock?:boolean};
const t=(slug:string,name:string,description:string,category:ToolDefinition["category"],mode:string,keywords:string[]=[],extra:Partial<ToolDefinition>={}):ToolDefinition=>({slug,name,description,category,mode,keywords,icon:"WandSparkles",...extra});
export const tools:ToolDefinition[]=[
 t("word-counter","Word Counter","Count words, characters, lines, and reading time.","Text","stats",["text","count"],{popular:true}),t("character-counter","Character Counter","Measure characters with and without spaces.","Text","chars"),t("case-converter","Case Converter","Transform text into the case you need.","Text","case",[],{popular:true}),t("remove-duplicate-lines","Remove Duplicate Lines","Clean repeated lines while preserving order.","Text","dedupe"),t("sort-lines","Sort Lines","Alphabetically sort text lines.","Text","sort"),t("slug-generator","Slug Generator","Create clean URL-friendly slugs.","Text","slug"),
 t("json-formatter","JSON Formatter","Format and inspect JSON instantly.","Developer","json-format",["prettify"],{popular:true}),t("json-validator","JSON Validator","Validate JSON with helpful errors.","Developer","json-valid"),t("base64-encoder-decoder","Base64 Encode / Decode","Convert text to and from Base64.","Developer","base64"),t("url-encoder-decoder","URL Encode / Decode","Safely encode or decode URL content.","Developer","url"),t("uuid-generator","UUID Generator","Generate secure UUID v4 identifiers.","Developer","uuid",[],{popular:true}),t("hash-generator","Hash Generator Mock","Preview a secure hashing workflow.","Developer","mock",[],{mock:true}),t("markdown-preview","Markdown Preview","Write Markdown and see a live preview.","Developer","markdown"),t("regex-tester","Regex Tester","Test expressions against sample text.","Developer","regex"),
 ...[["image-compressor","Image Compressor"],["image-resizer","Image Resizer"],["png-to-jpg","PNG to JPG"],["jpg-to-png","JPG to PNG"],["image-to-webp","Image to WebP"]].map(([s,n])=>t(s,n,"A polished browser-based image workflow.","Image","mock",[],{mock:true})),
 ...[["pdf-merge","PDF Merge"],["pdf-split","PDF Split"],["pdf-compress","PDF Compress"]].map(([s,n])=>t(s,n,"A private, client-first PDF workflow preview.","PDF","mock",[],{mock:true})),
 t("qr-generator","QR Generator Mock","Preview QR creation and export.","Utility","mock",[],{mock:true}),t("password-generator","Password Generator","Create strong, customizable passwords.","Utility","password",[],{popular:true}),t("timestamp-converter","Timestamp Converter","Convert Unix timestamps to readable dates.","Utility","timestamp")
];
export const toolBySlug=(slug:string)=>tools.find(x=>x.slug===slug);
export const searchTools=(q:string)=>{const n=q.toLowerCase().trim();return !n?tools:tools.filter(x=>[x.name,x.slug,x.category,x.description,...x.keywords].join(" ").toLowerCase().includes(n));};
