export const cn = (...classes: Array<string | false | null | undefined>) => classes.filter(Boolean).join(" ");
export const formatINR = (value: number, digits = 0) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: digits }).format(Number.isFinite(value) ? value : 0);
export const formatNumber = (value: number, digits = 0) => new Intl.NumberFormat("en-IN", { maximumFractionDigits: digits }).format(Number.isFinite(value) ? value : 0);
export const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

const normalizeSearch = (value: string) => value.toLocaleLowerCase("en-IN").normalize("NFKD").replace(/[^a-z0-9]+/g, " ").trim();
const editDistance = (left: string, right: string) => { const row = Array.from({ length: right.length + 1 }, (_, index) => index); for (let i = 1; i <= left.length; i += 1) { let diagonal = row[0]; row[0] = i; for (let j = 1; j <= right.length; j += 1) { const above = row[j]; row[j] = Math.min(row[j] + 1, row[j - 1] + 1, diagonal + (left[i - 1] === right[j - 1] ? 0 : 1)); diagonal = above; } } return row[right.length]; };
export function fuzzyScore(query: string, candidate: string): number { const needle = normalizeSearch(query); const haystack = normalizeSearch(candidate); if (!needle) return 1; if (haystack === needle) return 100; if (haystack.startsWith(needle)) return 80; if (haystack.includes(needle)) return 60; const queryTokens = needle.split(" "); const candidateTokens = haystack.split(" "); const matches = queryTokens.filter((token) => candidateTokens.some((word) => word.startsWith(token) || (token.length >= 3 && editDistance(token, word) <= Math.max(1, Math.floor(token.length / 4))))); return matches.length === queryTokens.length ? 30 + matches.length : 0; }
export function fuzzySearch<T>(items: T[], query: string, text: (item: T) => string): T[] { return items.map((item, index) => ({ item, index, score: fuzzyScore(query, text(item)) })).filter(({ score }) => score > 0).sort((a, b) => b.score - a.score || a.index - b.index).map(({ item }) => item); }
